language: node_js

node_js:
  - node

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

cache: yarn

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
