language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
